#!/usr/bin/env python3
"""Generate CATALOG.md from repository metadata.

    gh repo list OWNER --limit 300 --json name,description,url,pushedAt > repos.json
    python scripts/catalog.py repos.json > CATALOG.md
    python scripts/catalog.py --from-gh OWNER > CATALOG.md      # runs the gh command for you
"""
import argparse
import json
import os
import re
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
DEFAULT_RULES = os.path.join(HERE, "..", "categories.json")


def load_rules(path):
    with open(path, encoding="utf-8") as fh:
        data = json.load(fh)
    rules = [(r["category"], [re.compile(m, re.I) for m in r["match"]]) for r in data["rules"]]
    return rules, data.get("fallback", "Other")


def load_overrides(path):
    with open(path, encoding="utf-8") as fh:
        return json.load(fh).get("overrides", {})


def categorise(repo, rules, fallback, overrides=None):
    if overrides and repo["name"] in overrides:
        return overrides[repo["name"]]
    hay = "%s %s" % (repo["name"], repo.get("description") or "")
    for category, patterns in rules:
        if any(p.search(hay) for p in patterns):
            return category
    return fallback


def build(repos, rules, fallback, owner="", overrides=None):
    groups = {}
    for r in sorted(repos, key=lambda r: r["name"]):
        groups.setdefault(categorise(r, rules, fallback, overrides), []).append(r)
    known = [c for c, _ in rules]
    order = [c for c in known if c in groups] + sorted(c for c in groups if c not in known and c != fallback) + ([fallback] if fallback in groups else [])
    lines = ["# Catalog", "", "Generated by `scripts/catalog.py` from the repository list. Do not edit by hand: change `categories.json` and regenerate.", "",
             "**%d repositories** in %d categories." % (len(repos), len(order)), "", "| Category | Repositories |", "| --- | ---: |"]
    lines += ["| %s | %d |" % (c, len(groups[c])) for c in order]
    for c in order:
        lines += ["", "## %s" % c, "", "| Repository | What it does |", "| --- | --- |"]
        for r in groups[c]:
            desc = (r.get("description") or "").replace("|", "\\|").strip() or "(no description: add one)"
            url = r.get("url") or ("https://github.com/%s/%s" % (owner, r["name"]) if owner else r["name"])
            lines.append("| [%s](%s) | %s |" % (r["name"], url, desc))
    if fallback in groups:
        lines += ["", "> Repositories under **%s** matched no rule. Add a rule in `categories.json`." % fallback]
    return "\n".join(lines) + "\n"


def main(argv=None):
    p = argparse.ArgumentParser(description="Generate CATALOG.md from GitHub repository metadata.")
    p.add_argument("json_file", nargs="?", help="output of: gh repo list OWNER --json name,description,url")
    p.add_argument("--from-gh", metavar="OWNER", help="run gh repo list for OWNER instead of reading a file")
    p.add_argument("--rules", default=DEFAULT_RULES)
    a = p.parse_args(argv)
    if a.from_gh:
        raw = subprocess.run(["gh", "repo", "list", a.from_gh, "--limit", "500", "--json", "name,description,url"], capture_output=True, text=True, check=True).stdout
    elif a.json_file:
        with open(a.json_file, encoding="utf-8") as fh:
            raw = fh.read()
    else:
        p.error("give a JSON file or --from-gh OWNER")
    repos = json.loads(raw)
    rules, fallback = load_rules(a.rules)
    sys.stdout.write(build(repos, rules, fallback, a.from_gh or "", load_overrides(a.rules)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
